site_name: 北村たかゆき：政策リポジトリ
theme:
  name: material
  custom_dir: overrides
  language: ja
  palette:
    primary: pink
nav:
  - Home: 'index.md'
  - 'マニフェスト':
    - '1. 若者に選ばれるまち/多様性あふれるまち': 'manifest/diversity.md'
    - '2. 公民連携による教育/子どもを育てたいまちへ': 'manifest/education.md'
    - '3. 関市を支える経済の発展': 'manifest/economy.md'
    - '4. 将来も住み続けたい福祉医療防災の充実': 'manifest/care.md'
    - '5. 新規参入とIT技術を活用したバスの利便性向上': 'manifest/traffic.md'
    - '6. その他': 'manifest/others.md'
  - '議会から見る関市の数字': 'manifest/numbers.md'
  - '貢献したいあなたへ': 'contribution.md'
  - 'Issueマニュアル': 'manual_issue.md'
  - 'Pull Requestマニュアル': 'manual_pull_request.md'
