name: マニフェスト提言
description: マニフェスト提言用のテンプレート
body:
  - type: dropdown
    attributes:
      label: 政策ビジョン
      description: 該当する政策カテゴリを一つ選んでください
      multiple: true
      options:
        - 若者に選ばれるまち/多様性あふれるまち
        - 公民連携による教育/子どもを育てたいまちへ
        - 関市を支える経済の発展
        - 将来も住み続けたい福祉医療防災の充実
        - 新規参入とIT技術を活用したバスの利便性向上
        - その他
    validations:
      required: true
  - type: textarea
    attributes:
      label: 政策
      description: できる限りの記入をお願いします
    validations:
      required: true
  - type: textarea
    attributes:
      label: 必要だと思ったきっかけ
    validations:
      required: false
  - type: textarea
    attributes:
      label: なぜ必要か
    validations:
      required: false
  - type: textarea
    attributes:
      label: この Issue で議論したいこと
    validations:
      required: false
  - type: textarea
    attributes:
      label: 調べたこと（裏付けとなる事実・ファクト）
    validations:
      required: false
  - type: textarea
    attributes:
      label: 自由記述欄
    validations:
      required: false
